baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "NULLCONFIG"
  subtitle    = ""

  cover       = "background.jpg"
  description = "Here is a description of your site."
  metaDescription = "Ansible tutorials and tech blog"
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "digital_locust"
  fbName = ""
  githubName = "brgalloway"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Billy Galloway"
  authorAvatar = "uploads/profile.jpg"
  authorLocation = "Seattle, WA"
  authorWebsite = "https://nullconfig.com"
  authorDescription = "Devops Engineer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Blog"
  url = "/tags/blog/"
  weight = 100

[[menu.main]]
  name = "Ansible"
  url = "/categories/Ansible/"
  weight = 99

[[menu.main]]
  name = "Projects"
  url = "/categories/Projects/"
  weight = 95
